name: Attendance Tracker Backend PROD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: build-and-restart
        uses: appleboy/ssh-action@master
        env:
          GH_USER: ${{ secrets.GH_USER }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          host: "13.201.50.77"
          username: "ubuntu"
          envs: GH_USER,GH_TOKEN
          script: |
            cd backend/attendance-tracker-backend
            git pull https://${GH_USER}:${GH_TOKEN}@github.com/anuj-thakur-513/attendance-tracker-backend.git
            npm install
            npm run build-ts
            sudo pm2 reload dist/index.js
